-- Seed 20 blog posts for testing
-- Replace PROJECT_ID with your actual project ID

DO $$
DECLARE
  pid UUID := '00000000-0000-0000-0000-000000000000'; -- ← REPLACE WITH YOUR PROJECT ID
BEGIN

INSERT INTO blog_posts (project_id, slug, title, excerpt, categories, authors, status, published_at, blocks, seo, language) VALUES
(pid, 'come-scegliere-font-perfetto', 'Come scegliere il font perfetto per il tuo sito', 'La scelta del font giusto può fare la differenza tra un sito amatoriale e uno professionale. Ecco i nostri consigli.', '["Design", "Tutorial"]', '["Marco Rossi"]', 'published', now() - interval '1 day', '[{"id":"t1","type":"text","content":{"text":"<p>La tipografia è uno degli elementi più importanti del web design. Un font ben scelto comunica professionalità e migliora la leggibilità.</p><h2>Regole base</h2><p>Usa massimo 2 font diversi. Uno per i titoli e uno per il corpo del testo. Assicurati che siano leggibili anche su mobile.</p>"},"style":{}}]', '{"title":"Come scegliere il font perfetto","description":"Guida pratica alla scelta del font per il tuo sito web"}', 'it'),

(pid, 'seo-locale-guida-completa', 'SEO Locale: la guida completa per farsi trovare', 'Tutto quello che devi sapere per posizionare la tua attività locale su Google Maps e nei risultati di ricerca.', '["SEO", "Marketing"]', '["Sara Bianchi"]', 'published', now() - interval '2 days', '[{"id":"t2","type":"text","content":{"text":"<p>Il SEO locale è fondamentale per qualsiasi attività che serve clienti in una zona geografica specifica.</p><h2>Google My Business</h2><p>Il primo passo è creare e ottimizzare il tuo profilo Google My Business.</p>"},"style":{}}]', '{"title":"SEO Locale: guida completa","description":"Come posizionare la tua attività locale su Google"}', 'it'),

(pid, 'tendenze-web-design-2026', 'Le 10 tendenze del web design nel 2026', 'Dal design brutale al minimalismo estremo: scopri cosa va di moda quest anno nel mondo del web design.', '["Design", "Tendenze"]', '["Marco Rossi"]', 'published', now() - interval '3 days', '[{"id":"t3","type":"text","content":{"text":"<p>Il 2026 porta con sé nuove tendenze che stanno ridefinendo il modo in cui progettiamo i siti web.</p><h2>1. Minimalismo estremo</h2><p>Meno è più. I siti più efficaci usano spazi bianchi generosi e tipografia bold.</p>"},"style":{}}]', '{"title":"Tendenze web design 2026","description":"Le 10 tendenze del web design più importanti di quest anno"}', 'it'),

(pid, 'velocita-sito-web-importanza', 'Perché la velocità del sito è cruciale per il tuo business', 'Un secondo di ritardo nel caricamento può costare il 7% delle conversioni. Ecco come velocizzare il tuo sito.', '["Performance", "Tutorial"]', '["Luca Verdi"]', 'published', now() - interval '4 days', '[{"id":"t4","type":"text","content":{"text":"<p>La velocità di caricamento è un fattore critico per il successo online. Google la usa come fattore di ranking.</p><h2>Core Web Vitals</h2><p>Concentrati su LCP, FID e CLS per migliorare le prestazioni.</p>"},"style":{}}]', '{"title":"Velocità del sito web","description":"Come la velocità del sito impatta sul tuo business"}', 'it'),

(pid, 'colori-psicologia-web', 'La psicologia dei colori nel web design', 'Ogni colore evoca emozioni diverse. Scopri come usarli strategicamente nel tuo sito.', '["Design", "Marketing"]', '["Sara Bianchi"]', 'published', now() - interval '5 days', '[{"id":"t5","type":"text","content":{"text":"<p>I colori non sono solo estetici — influenzano le decisioni degli utenti. Il blu trasmette fiducia, il rosso urgenza.</p><h2>Come scegliere la palette</h2><p>Parti dal tuo brand e scegli 3-4 colori complementari.</p>"},"style":{}}]', '{"title":"Psicologia dei colori nel web","description":"Come i colori influenzano il comportamento degli utenti"}', 'it'),

(pid, 'google-analytics-guida-base', 'Google Analytics 4: guida per principianti', 'Impara a leggere i dati del tuo sito e a prendere decisioni basate sui numeri.', '["Analytics", "Tutorial"]', '["Luca Verdi"]', 'published', now() - interval '6 days', '[{"id":"t6","type":"text","content":{"text":"<p>Google Analytics 4 è lo strumento essenziale per capire come gli utenti interagiscono con il tuo sito.</p><h2>Primi passi</h2><p>Dopo aver installato il tag, concentrati su sessioni, utenti e tasso di rimbalzo.</p>"},"style":{}}]', '{"title":"Google Analytics 4 per principianti","description":"Guida base a Google Analytics 4"}', 'it'),

(pid, 'mobile-first-design', 'Mobile First: perché progettare prima per mobile', 'Il 70% del traffico web viene da mobile. Ecco perché il design mobile-first non è più opzionale.', '["Design", "Performance"]', '["Marco Rossi", "Sara Bianchi"]', 'published', now() - interval '7 days', '[{"id":"t7","type":"text","content":{"text":"<p>Progettare mobile-first significa partire dall esperienza più limitata e poi espandere per schermi più grandi.</p><h2>Vantaggi</h2><p>Migliore performance, migliore UX, migliore SEO.</p>"},"style":{}}]', '{"title":"Mobile First Design","description":"Perché progettare prima per mobile è fondamentale"}', 'it'),

(pid, 'copywriting-sito-web', '7 regole di copywriting per il tuo sito', 'Le parole giuste possono raddoppiare le conversioni. Ecco le regole d oro del copywriting web.', '["Copywriting", "Marketing"]', '["Sara Bianchi"]', 'published', now() - interval '8 days', '[{"id":"t8","type":"text","content":{"text":"<p>Il copywriting web è diverso dalla scrittura tradizionale. Deve essere scannable, conciso e orientato all azione.</p><h2>Regola 1: Titoli che catturano</h2><p>L 80% delle persone legge solo il titolo. Rendilo irresistibile.</p>"},"style":{}}]', '{"title":"Copywriting per siti web","description":"7 regole per scrivere testi che convertono"}', 'it'),

(pid, 'ssl-certificato-https', 'HTTPS e SSL: perché il tuo sito ne ha bisogno', 'Un sito senza HTTPS perde fiducia e posizionamento. Ecco come attivare il certificato SSL.', '["Sicurezza", "SEO"]', '["Luca Verdi"]', 'published', now() - interval '9 days', '[{"id":"t9","type":"text","content":{"text":"<p>HTTPS non è più opzionale. Google penalizza i siti senza SSL e i browser mostrano avvisi di sicurezza.</p><h2>Come attivare SSL</h2><p>La maggior parte degli hosting offre certificati SSL gratuiti tramite Let s Encrypt.</p>"},"style":{}}]', '{"title":"HTTPS e certificati SSL","description":"Perché il tuo sito ha bisogno di HTTPS"}', 'it'),

(pid, 'landing-page-efficace', 'Come creare una landing page che converte', 'Anatomia di una landing page perfetta: dalla hero alla CTA, ogni elemento conta.', '["Marketing", "Tutorial"]', '["Marco Rossi"]', 'published', now() - interval '10 days', '[{"id":"t10","type":"text","content":{"text":"<p>Una landing page efficace ha un solo obiettivo: convertire il visitatore in cliente.</p><h2>Struttura vincente</h2><p>Hero con proposta di valore, social proof, benefici, CTA ripetuta.</p>"},"style":{}}]', '{"title":"Landing page che converte","description":"Come creare landing page efficaci"}', 'it'),

(pid, 'immagini-ottimizzazione-web', 'Ottimizzare le immagini per il web: guida pratica', 'Immagini pesanti rallentano il sito. Ecco come ridurre il peso senza perdere qualità.', '["Performance", "Tutorial"]', '["Luca Verdi"]', 'published', now() - interval '11 days', '[{"id":"t11","type":"text","content":{"text":"<p>Le immagini rappresentano in media il 50% del peso di una pagina web.</p><h2>Formato WebP</h2><p>WebP offre compressione superiore a JPEG e PNG con qualità comparabile.</p>"},"style":{}}]', '{"title":"Ottimizzazione immagini web","description":"Come ridurre il peso delle immagini senza perdere qualità"}', 'it'),

(pid, 'accessibilita-web-basi', 'Accessibilità web: le basi che ogni sito dovrebbe avere', 'Rendere il tuo sito accessibile non è solo etico — è anche buono per il SEO e il business.', '["Design", "Accessibilità"]', '["Sara Bianchi"]', 'published', now() - interval '12 days', '[{"id":"t12","type":"text","content":{"text":"<p>L accessibilità web significa che tutti, incluse le persone con disabilità, possono usare il tuo sito.</p><h2>Alt text per immagini</h2><p>Ogni immagine deve avere un testo alternativo descrittivo.</p>"},"style":{}}]', '{"title":"Accessibilità web: le basi","description":"Come rendere il tuo sito accessibile a tutti"}', 'it'),

(pid, 'social-media-integrazione', 'Come integrare i social media nel tuo sito', 'Dal feed Instagram al bottone WhatsApp: le migliori integrazioni social per il tuo sito.', '["Social", "Marketing"]', '["Marco Rossi"]', 'published', now() - interval '13 days', '[{"id":"t13","type":"text","content":{"text":"<p>I social media e il sito web devono lavorare insieme per massimizzare la visibilità online.</p><h2>Feed Instagram</h2><p>Mostra le ultime foto direttamente sul sito per tenere il contenuto fresco.</p>"},"style":{}}]', '{"title":"Social media e sito web","description":"Come integrare i social media nel tuo sito web"}', 'it'),

(pid, 'errori-comuni-sito-web', 'I 5 errori più comuni nei siti di piccole attività', 'Evita questi errori che rovinano la credibilità del tuo sito e allontanano i clienti.', '["Business", "Tutorial"]', '["Sara Bianchi"]', 'published', now() - interval '14 days', '[{"id":"t14","type":"text","content":{"text":"<p>Molte piccole attività commettono errori evitabili che danneggiano la loro presenza online.</p><h2>Errore 1: Nessuna call-to-action</h2><p>Ogni pagina deve guidare il visitatore verso un azione specifica.</p>"},"style":{}}]', '{"title":"5 errori comuni nei siti web","description":"Gli errori più frequenti nei siti di piccole attività"}', 'it'),

(pid, 'email-marketing-base', 'Email marketing: come iniziare da zero', 'Costruisci la tua lista email e trasforma i visitatori del sito in clienti fedeli.', '["Marketing", "Tutorial"]', '["Luca Verdi"]', 'published', now() - interval '15 days', '[{"id":"t15","type":"text","content":{"text":"<p>L email marketing rimane il canale con il ROI più alto: per ogni euro investito ne tornano 42.</p><h2>Step 1: Scegli una piattaforma</h2><p>Mailchimp, Brevo o ConvertKit sono ottimi per iniziare gratuitamente.</p>"},"style":{}}]', '{"title":"Email marketing da zero","description":"Guida per iniziare con l email marketing"}', 'it'),

(pid, 'gdpr-sito-web-cookies', 'GDPR e cookies: cosa deve fare il tuo sito', 'La compliance GDPR non è opzionale. Ecco cosa serve per essere in regola.', '["Legale", "Sicurezza"]', '["Sara Bianchi"]', 'published', now() - interval '16 days', '[{"id":"t16","type":"text","content":{"text":"<p>Il GDPR richiede che ogni sito web che tratta dati di cittadini EU sia conforme.</p><h2>Cookie banner</h2><p>Devi mostrare un banner che permette agli utenti di accettare o rifiutare i cookie.</p>"},"style":{}}]', '{"title":"GDPR e cookies","description":"Cosa deve fare il tuo sito per il GDPR"}', 'it'),

(pid, 'call-to-action-efficaci', 'Come scrivere CTA che funzionano davvero', 'Il pulsante giusto con le parole giuste nel posto giusto. La scienza dietro le call-to-action.', '["Copywriting", "Design"]', '["Marco Rossi", "Luca Verdi"]', 'published', now() - interval '17 days', '[{"id":"t17","type":"text","content":{"text":"<p>Una CTA efficace è chiara, urgente e visivamente prominente.</p><h2>Parole che convertono</h2><p>Usa verbi d azione: Scopri, Inizia, Prenota, Scarica. Evita il generico Clicca qui.</p>"},"style":{}}]', '{"title":"CTA che funzionano","description":"Come scrivere call-to-action efficaci"}', 'it'),

(pid, 'fotografia-prodotto-fai-da-te', 'Fotografia prodotto fai-da-te per il tuo sito', 'Non servono migliaia di euro per avere foto prodotto professionali. Ecco come fare con il tuo smartphone.', '["Tutorial", "Business"]', '["Luca Verdi"]', 'published', now() - interval '18 days', '[{"id":"t18","type":"text","content":{"text":"<p>Foto di qualità aumentano le vendite del 30%. E oggi puoi farle con uno smartphone.</p><h2>Setup base</h2><p>Luce naturale vicino a una finestra, sfondo bianco, treppiede economico.</p>"},"style":{}}]', '{"title":"Fotografia prodotto fai-da-te","description":"Come fare foto prodotto professionali con lo smartphone"}', 'it'),

(pid, 'google-maps-attivita-locale', 'Google Maps: come far trovare la tua attività', 'Dalla scheda Google My Business alle recensioni: massimizza la visibilità su Maps.', '["SEO", "Business"]', '["Sara Bianchi"]', 'published', now() - interval '19 days', '[{"id":"t19","type":"text","content":{"text":"<p>Google Maps è spesso il primo punto di contatto tra un cliente e la tua attività.</p><h2>Ottimizza la scheda</h2><p>Foto aggiornate, orari corretti, rispondi a tutte le recensioni.</p>"},"style":{}}]', '{"title":"Google Maps per attività locali","description":"Come ottimizzare la presenza su Google Maps"}', 'it'),

(pid, 'dominio-hosting-guida', 'Dominio e hosting: come scegliere senza sbagliare', 'La guida definitiva per scegliere dominio e hosting per il tuo primo sito web.', '["Tutorial", "Tendenze"]', '["Marco Rossi"]', 'draft', null, '[{"id":"t20","type":"text","content":{"text":"<p>Il dominio è il tuo indirizzo online, l hosting è lo spazio dove vive il tuo sito.</p><h2>Dominio</h2><p>Scegli un .it o .com, corto e facile da ricordare.</p>"},"style":{}}]', '{"title":"Dominio e hosting: guida","description":"Come scegliere dominio e hosting per il tuo sito"}', 'it');

END $$;
